# Generated by Django 4.2.7 on 2023-11-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
