# Generated by Django 4.2.7 on 2023-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options_alter_article_anouncement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('ФП', 'Фактическая погода'), ('ПП', 'Прогноз погоды'), ('ШО', 'Штормовое оповещение'), ('ШП', 'Штормовое предупреждение')], max_length=20, verbose_name='Категория сообщения'),
        ),
    ]
