# Generated by Django 4.2.7 on 2024-01-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_category_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/%Y/%m/%d/'),
        ),
    ]
