# Generated by Django 4.2.7 on 2023-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='point',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AddField(
            model_name='account',
            name='post',
            field=models.CharField(choices=[('НМтС', 'Начальник метеослужбы'), ('НС', 'Начальник смены'), ('ИС', 'Инженер-синоптик'), ('МН', 'Метеонаблюдатель'), ('N/A', 'Not answered')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
