# Generated by Django 4.2.7 on 2023-12-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_gender_account_point_account_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['user', 'point'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
