# Generated by Django 4.2.7 on 2024-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='post',
            field=models.CharField(choices=[('N/A', 'Not answered'), ('НМтС', 'Начальник метеослужбы'), ('НС', 'Начальник смены'), ('ИС', 'Инженер-синоптик'), ('МН', 'Метеонаблюдатель')], max_length=20),
        ),
    ]
