# Generated by Django 4.2.7 on 2024-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='point',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='post',
            field=models.CharField(choices=[('N/A', 'Not answered'), ('НМтС', 'Начальник метеослужбы'), ('НС', 'Начальник смены'), ('ИС', 'Инженер-синоптик'), ('МН', 'Метеонаблюдатель')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
